import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Himf from '../public/assests/imt.png'

const Hero = () => {
  return (
    <>
    <div>
    
      <Head>
    
        <title>MediaCaris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="http://fonts.cdnfonts.com/css/clash-display" rel="stylesheet"/>
                

      </Head>
      </div>
    
      <div className="relative overflow-hidden bg-wihte p-10">
    <div className="mx-auto max-w-7xl">
      <div className="relative  bg-wihte  sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32">
    
       <main className="mx-auto mt-10 max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">

          <div className="sm:text-center lg:text-left ml-9">

            <h1 className="text-4xl font-semi-bold  text-gray-900 sm:text-5xl md:text-5xl tracking-widest">
              <span className="block xl:inline">We Help You <span className="block text-blue-500 xl:inline">Grow<br></br></span>Your Business</span>      
            </h1>

            <p className="mt-3 text-base text-gray-500 sm:mx-auto sm:mt-5 sm:max-w-xl sm:text-lg md:mt-5 md:text-x lg:mx-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet sodales lacus libero aliquet. Sed tincidunt ut a molestie ornare. Fermentum purus ullamcorper nunc </p>
            <div className="mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start">
              <div className="rounded-md shadow">
                <a href="#" className="flex w-full items-center justify-center rounded-md border border-transparent bg-blue-500 px-8 py-3 text-base font-medium text-white  md:py-2 md:px-5 md:text-lg ">OUR SERVICES</a>
            </div>
              <div className="mt-3 sm:mt-0 sm:ml-3">
                <a href="#" className=" w-full items-center justify-center rounded-md   bg-transparent px-8 py-3 text-base font-medium text-blue-500  md:py-2 md:px-5 md:text-lg flex gap-3">CONTACT US
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6">
                  <path fillRule="evenodd" d="M16.72 7.72a.75.75 0 011.06 0l3.75 3.75a.75.75 0 010 1.06l-3.75 3.75a.75.75 0 11-1.06-1.06l2.47-2.47H3a.75.75 0 010-1.5h16.19l-2.47-2.47a.75.75 0 010-1.06z" clipRule="evenodd" />
                  </svg></a>
              </div>
            </div>
          </div>
        </main>
        
       
        
      </div>
      <div className="lg:absolute lg:inset-y-8 lg:right-20 lg:w-1/3  z-5  ">
      <Image className="h-56 w-full object-cover sm:h-72 md:h-96 lg:h-full lg:w-full " src={Himf} alt=""/>
        </div>
    </div>
   
  </div>
  
  </>
   
  )
}

export default Hero